apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manager
  namespace: catalyst-order-workflow-demo
  labels:
    app: order-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-manager
  template:
    metadata:
      labels:
        app: order-manager
    spec:
      containers:
        - name: order-manager
          image: public.ecr.aws/e9f1v8j5/catalyst-demo/order-manager:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DAPR_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: catalyst-app-tokens
                  key: order-manager
            - name: DAPR_APP_CALLBACK_URL
              value: "http://demo-production-catalyst.westeurope.cloudapp.azure.com:8081"
          envFrom:
            - configMapRef:
                name: catalyst-env
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-manager
  labels:
    app: order-manager
spec:
  selector:
    app: order-manager
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP